# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaEmergente.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import csv
from PyQt5 import QtCore, QtGui, QtWidgets


class uiAgregarCarrito(object):
    def __init__(self, idProducto):
            self.idProducto = idProducto
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 206)
        MainWindow.setMinimumSize(QtCore.QSize(400, 206))
        MainWindow.setMaximumSize(QtCore.QSize(400, 206))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 421, 201))
        self.frame.setMinimumSize(QtCore.QSize(431, 201))
        self.frame.setMaximumSize(QtCore.QSize(431, 201))
        self.frame.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelTitulo = QtWidgets.QLabel(self.frame)
        self.labelTitulo.setGeometry(QtCore.QRect(50, 20, 320, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setStyleSheet("")
        self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitulo.setObjectName("labelTitulo")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setGeometry(QtCore.QRect(150, 70, 111, 41))
        self.spinBox.setObjectName("spinBox")

        #Boton guardar
        self.btnGuardar = QtWidgets.QPushButton(self.frame)
        self.btnGuardar.setGeometry(QtCore.QRect(170, 140, 75, 23))
        self.btnGuardar.setObjectName("pushButton")

        #Accion boton guardar
        self.btnGuardar.clicked.connect(self.cambiar_a_ventana_anterior)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Agregar Stock"))
        self.labelTitulo.setText(_translate("MainWindow", "¿Cuanto productos quiere agregar?"))
        self.btnGuardar.setText(_translate("MainWindow", "Agregar"))


    def cambiar_a_ventana_anterior(self):
        self.ventanaActual = QtWidgets.QApplication.activeWindow()
        self.ventanaActual.close()
        from uiVentaProductos import uiVentaProductos  
        self.ventanaAnterior = QtWidgets.QMainWindow(self.ventanaActual.parent())
        self.uiVentanaAnterior = uiVentaProductos()
        self.uiVentanaAnterior.setupUi(self.ventanaAnterior)
        self.ventanaAnterior.show()
    
    
    



