from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
import sys
import csv
# import PyQt5.QtWidgets as qtw
from PyQt5 import QtWidgets
from Articulos import *

class uiCrearProducto(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1291, 701))
        self.frame.setMinimumSize(QtCore.QSize(1291, 701))
        self.frame.setMaximumSize(QtCore.QSize(1291, 701))
        self.frame.setStyleSheet("background-color: rgb(38, 87, 165);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelTitulo = QtWidgets.QLabel(self.frame)
        self.labelTitulo.setGeometry(QtCore.QRect(362, 45, 528, 55))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 27px;")
        self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitulo.setObjectName("labelTitulo")
        self.btnAtras = QtWidgets.QPushButton(self.frame)
        self.btnAtras.setGeometry(QtCore.QRect(30, 24, 66, 49))
        self.btnAtras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAtras.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnAtras.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.btnAtras.setText("")
        self.btnAtras.setObjectName("btnAtras")
        self.labelAtras = QtWidgets.QLabel(self.frame)
        self.labelAtras.setGeometry(QtCore.QRect(30, 24, 66, 49))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelAtras.setFont(font)
        self.labelAtras.setStyleSheet("")
        self.labelAtras.setText("")
        self.labelAtras.setPixmap(QtGui.QPixmap("imagenes/Logo Atras.png"))
        self.labelAtras.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAtras.setObjectName("labelAtras")
        self.labelNombre = QtWidgets.QLabel(self.frame)
        self.labelNombre.setGeometry(QtCore.QRect(61, 127, 174, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelNombre.setFont(font)
        self.labelNombre.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 16px;")
        self.labelNombre.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNombre.setObjectName("labelNombre")
        self.labelLogo = QtWidgets.QLabel(self.frame)
        self.labelLogo.setGeometry(QtCore.QRect(360, 130, 533, 503))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelLogo.setFont(font)
        self.labelLogo.setStyleSheet("")
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("imagenes/Icono Fondo.png"))
        self.labelLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogo.setObjectName("labelLogo")
        self.inputNombre = QtWidgets.QLineEdit(self.frame)
        self.inputNombre.setGeometry(QtCore.QRect(254, 127, 646, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.inputNombre.setFont(font)
        self.inputNombre.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.inputNombre.setText("")
        self.inputNombre.setObjectName("inputNombre")
        self.labelID = QtWidgets.QLabel(self.frame)
        self.labelID.setGeometry(QtCore.QRect(61, 178, 174, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelID.setFont(font)
        self.labelID.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 16px;")
        self.labelID.setAlignment(QtCore.Qt.AlignCenter)
        self.labelID.setObjectName("labelID")
        self.inputID = QtWidgets.QLineEdit(self.frame)
        self.inputID.setGeometry(QtCore.QRect(254, 178, 646, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.inputID.setFont(font)
        self.inputID.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.inputID.setText("")
        self.inputID.setObjectName("inputID")
        self.labelMascota = QtWidgets.QLabel(self.frame)
        self.labelMascota.setGeometry(QtCore.QRect(61, 229, 174, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelMascota.setFont(font)
        self.labelMascota.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 16px;")
        self.labelMascota.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMascota.setObjectName("labelMascota")
        self.labelMarca = QtWidgets.QLabel(self.frame)
        self.labelMarca.setGeometry(QtCore.QRect(61, 331, 174, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelMarca.setFont(font)
        self.labelMarca.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 16px;")
        self.labelMarca.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMarca.setObjectName("labelMarca")
        self.labelCategoria = QtWidgets.QLabel(self.frame)
        self.labelCategoria.setGeometry(QtCore.QRect(61, 382, 174, 33))
        # self.labelTelefono = QtWidgets.QLabel(self.frame)
        # self.labelTelefono.setGeometry(QtCore.QRect(61, 484, 174, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelCategoria.setFont(font)
        self.labelCategoria.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 16px;")
        self.labelCategoria.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCategoria.setObjectName("labelCategoria")
        self.labelPrecio = QtWidgets.QLabel(self.frame)
        self.labelPrecio.setGeometry(QtCore.QRect(61, 433, 174, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelPrecio.setFont(font)
        self.labelPrecio.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 16px;")
        self.labelPrecio.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecio.setObjectName("labelPrecio")
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.inputMascota = QtWidgets.QLineEdit(self.frame)
        self.inputMascota.setGeometry(QtCore.QRect(254, 229, 646, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.inputMascota.setFont(font)
        self.inputMascota.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.inputMascota.setText("")
        self.inputMascota.setObjectName("inputMascota")
        self.inputMarca = QtWidgets.QLineEdit(self.frame)
        self.inputMarca.setGeometry(QtCore.QRect(254, 331, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.inputMarca.setFont(font)
        self.inputMarca.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.inputMarca.setText("")
        self.inputMarca.setObjectName("inputCorreo")
        self.inputPrecio = QtWidgets.QLineEdit(self.frame)
        self.inputPrecio.setGeometry(QtCore.QRect(254, 433, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.inputPrecio.setFont(font)
        self.inputPrecio.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.inputPrecio.setText("")
        self.inputPrecio.setMaxLength(8)
        self.inputPrecio.setObjectName("inputPrecio")
        font = QtGui.QFont()
        self.labelPrecioLote = QtWidgets.QLabel(self.frame)
        self.labelPrecioLote.setGeometry(QtCore.QRect(61, 280, 174, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelPrecioLote.setFont(font)
        self.labelPrecioLote.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 16px;")
        self.labelPrecioLote.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecioLote.setObjectName("labelPrecioLote")
        self.labelStock = QtWidgets.QLabel(self.frame)
        self.labelStock.setGeometry(QtCore.QRect(61, 484, 174, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelStock.setFont(font)
        self.labelStock.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 16px;")
        self.labelStock.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStock.setObjectName("labelStock")
        self.inputPrecioLote = QtWidgets.QLineEdit(self.frame)
        self.inputPrecioLote.setGeometry(QtCore.QRect(254, 280, 646, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.inputPrecioLote.setFont(font)
        self.inputPrecioLote.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.inputPrecioLote.setText("")
        self.inputPrecioLote.setObjectName("inputPrecioLote")
        self.inputStock = QtWidgets.QLineEdit(self.frame)
        self.inputStock.setGeometry(QtCore.QRect(254, 484, 646, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.inputStock.setFont(font)
        self.inputStock.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.inputStock.setText("")
        self.inputStock.setObjectName("inputStock")
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.labelLimCritico = QtWidgets.QLabel(self.frame)
        self.labelLimCritico.setGeometry(QtCore.QRect(61, 533, 174, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelLimCritico.setFont(font)
        self.labelLimCritico.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 16px;")
        self.labelLimCritico.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLimCritico.setObjectName("labelLimCritico")
        self.inputLimCritico = QtWidgets.QLineEdit(self.frame)
        self.inputLimCritico.setGeometry(QtCore.QRect(254, 533, 646, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.inputLimCritico.setFont(font)
        self.inputLimCritico.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.inputLimCritico.setText("")
        self.inputLimCritico.setObjectName("inputLimCritico")
        self.labelDescripcion = QtWidgets.QLabel(self.frame)
        self.labelDescripcion.setGeometry(QtCore.QRect(61, 584, 174, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelDescripcion.setFont(font)
        self.labelDescripcion.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 16px;")
        self.labelDescripcion.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDescripcion.setObjectName("labelLimCritico")
        self.inputDescripcion = QtWidgets.QTextEdit(self.frame)
        self.inputDescripcion.setGeometry(QtCore.QRect(254, 584, 646, 60))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.inputDescripcion.setFont(font)
        self.inputDescripcion.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.inputDescripcion.setText("")
        self.inputDescripcion.setObjectName("inputLimCritico")
        self.comboBoxC = QtWidgets.QComboBox(self.frame)
        self.comboBoxC.setGeometry(QtCore.QRect(254, 382, 641, 31))
        self.comboBoxC.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxC.setObjectName("comboBoxG")
        self.comboBoxC.addItem("Articulos de Aceo")
        self.comboBoxC.setFont(font)
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxC.addItem("Prendas de Ropa")
        self.comboBoxC.addItem("Juguetes de Relajacion")
        self.comboBoxC.addItem("Alimentos y Suplementos")
        self.comboBoxC.addItem("Accesorios de Paseo")
        self.comboBoxC.addItem("Juguetes de Entretenimiento")
        self.comboBoxC.addItem("Nidos y Muebles")
        self.comboBoxC.addItem("Cestas")
        
        #raise
        self.labelLogo.raise_()
        self.labelAtras.raise_()
        self.labelTitulo.raise_()
        self.btnAtras.raise_()
        self.labelNombre.raise_()
        self.inputNombre.raise_()
        self.labelID.raise_()
        self.inputID.raise_()
        self.labelMascota.raise_()
        self.labelMarca.raise_()
        self.labelCategoria.raise_()
        self.labelPrecio.raise_()
        self.labelStock.raise_()
        self.labelPrecioLote.raise_()
        self.labelLimCritico.raise_()
        self.inputMascota.raise_()
        self.labelDescripcion.raise_()
        self.inputMarca.raise_()
        self.inputPrecio.raise_()
        self.inputStock.raise_()
        self.inputPrecioLote.raise_()
        self.inputLimCritico.raise_()
        self.inputDescripcion.raise_()
        self.comboBoxC.raise_()
        self.btnRegistrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegistrar.setGeometry(QtCore.QRect(983, 620, 247, 48))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnRegistrar.setFont(font)
        self.btnRegistrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRegistrar.setStyleSheet("border-color: rgb(0, 74, 173);")
        self.btnRegistrar.setObjectName("btnRegistrar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clinica CVI"))
        self.labelTitulo.setText(_translate("MainWindow", "CREAR PRODUCTO"))
        self.labelNombre.setText(_translate("MainWindow", "Nombre"))
        self.inputNombre.setPlaceholderText(_translate("MainWindow", "Nombre(s) del Producto..."))
        self.labelID.setText(_translate("MainWindow", "ID"))
        self.inputID.setPlaceholderText(_translate("MainWindow", "ID del producto..."))
        self.labelMascota.setText(_translate("MainWindow", "Mascota"))
        self.labelMarca.setText(_translate("MainWindow", "Marca"))
        self.labelCategoria.setText(_translate("MainWindow", "Categoria"))
        self.labelPrecio.setText(_translate("MainWindow", "Precio"))
        self.labelStock.setText(_translate("MainWindow", "Stock"))
        self.labelPrecioLote.setText(_translate("MainWindow", "Precio Lote"))
        self.labelLimCritico.setText(_translate("MainWindow", "Limite Critico"))
        self.labelDescripcion.setText(_translate("MainWindow", "Descripcion"))
        self.inputMascota.setPlaceholderText(_translate("MainWindow", "Tipo de Mascota..."))
        self.inputMarca.setPlaceholderText(_translate("MainWindow", "Marca del Producto..."))
        self.inputPrecio.setPlaceholderText(_translate("MainWindow", "Precio del Producto..."))
        self.inputLimCritico.setPlaceholderText(_translate("MainWindow", "Limite Critico del producto..."))
        self.inputStock.setPlaceholderText(_translate("MainWindow", "Cantidad de productos"))
        self.inputPrecioLote.setPlaceholderText(_translate("MainWindow", "Precio por lote"))
        self.inputDescripcion.setPlaceholderText(_translate("MainWindow", "Breve descripcion del producto..."))
        self.btnRegistrar.setText(_translate("MainWindow", "Guardar"))

        self.btnAtras.clicked.connect(lambda:self.ventana_anterior())


        self.btnRegistrar.clicked.connect(self.agregar_articulos)
    
        regex = QRegExp("[a-zA-Z ]+")
        regexNumeros = QRegExp("[0-9]+")
        
        self.validador = QRegExpValidator(regex)
        self.validadorNumeros = QRegExpValidator(regexNumeros)
        
        self.inputNombre.setValidator(self.validador)
        self.inputMascota.setValidator(self.validador)
        self.inputPrecio.setValidator(self.validadorNumeros)
        self.inputStock.setValidator(self.validadorNumeros)
        self.inputPrecioLote.setValidator(self.validadorNumeros)
        self.inputLimCritico.setValidator(self.validadorNumeros)
    


    def ventana_anterior(self):
        self.ventanaActual = QtWidgets.QApplication.activeWindow()
        self.ventanaActual.close()
        from uiListaProductos import uiListaProductos  # Importación local para evitar el ciclo de importación
        self.ventanaAnterior = QtWidgets.QMainWindow(self.ventanaActual.parent())
        self.uiVentanaAnterior = uiListaProductos()
        self.uiVentanaAnterior.setupUi(self.ventanaAnterior)
        self.ventanaAnterior.show()
        
        

    def agregar_articulos(self):
        nombre = self.inputNombre.text()
        mascota = self.inputMascota.text()
        id = self.inputID.text()
        marca = self.inputMarca.text()
        precio = self.inputPrecio.text()
        stock = self.inputStock.text()
        descripcion = self.inputDescripcion.toPlainText()
        categoria = self.comboBoxC.currentText()
        precioLote = self.inputPrecioLote.text()
        limiteCritico = self.inputLimCritico.text()

        if nombre == '' or id == '' or mascota == '' or id == '' or marca == '' or precio == '' or stock == '' or descripcion == '' or precioLote == '' or limiteCritico == '':
            QMessageBox.critical(self, "Error", "Por favor, complete todos los campos requeridos.")
            return

        articulo = Articulos(nombre, mascota, id, marca, precio, stock, descripcion, categoria, precioLote, limiteCritico)
        articulo.AgregarArticulo(nombre, mascota, id, marca, precio, stock, descripcion, categoria, precioLote, limiteCritico)
        self.ventana_anterior()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = uiCrearProducto()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())