# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'devoluciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1291, 720))
        self.frame.setMinimumSize(QtCore.QSize(1291, 720))
        self.frame.setMaximumSize(QtCore.QSize(1291, 720))
        self.frame.setStyleSheet("background-color: rgb(38, 87, 165);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelTitulo = QtWidgets.QLabel(self.frame)
        self.labelTitulo.setGeometry(QtCore.QRect(355, 50, 528, 54))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.labelTitulo.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 27px;")
        self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitulo.setObjectName("labelTitulo")
        self.label2 = QtWidgets.QLabel(self.frame)
        self.label2.setGeometry(QtCore.QRect(570, 120, 691, 519))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #000000;")
        self.label2.setText("")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.inputID = QtWidgets.QLineEdit(self.frame)
        self.inputID.setGeometry(QtCore.QRect(30, 230, 351, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        self.inputID.setFont(font)
        self.inputID.setStyleSheet("border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.inputID.setText("")
        self.inputID.setObjectName("inputID")
        self.labelTituloID = QtWidgets.QLabel(self.frame)
        self.labelTituloID.setGeometry(QtCore.QRect(30, 180, 281, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.labelTituloID.setFont(font)
        self.labelTituloID.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.labelTituloID.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 18px;")
        self.labelTituloID.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloID.setObjectName("labelTituloID")
        self.btnFiltrar = QtWidgets.QPushButton(self.frame)
        self.btnFiltrar.setGeometry(QtCore.QRect(320, 640, 205, 55))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnFiltrar.setFont(font)
        self.btnFiltrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFiltrar.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-radius: 27px")
        self.btnFiltrar.setObjectName("btnFiltrar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitulo.setText(_translate("MainWindow", "DEVOLUCIONES"))
        self.inputID.setPlaceholderText(_translate("MainWindow", "Ingrese Id de transacción:"))
        self.labelTituloID.setText(_translate("MainWindow", "Id de transacción"))
        self.btnFiltrar.setText(_translate("MainWindow", "Filtrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
