# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from uiListaProductos import uiListaProductos
from uiVentaProductos import uiVentaProductos
from uiCrearCliente import uiCrearCliente

class uiMenu (object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1280, 720)
                MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
                MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.frame = QtWidgets.QFrame(self.centralwidget)
                self.frame.setGeometry(QtCore.QRect(0, 0, 1291, 720))
                self.frame.setMinimumSize(QtCore.QSize(1291, 720))
                self.frame.setMaximumSize(QtCore.QSize(1291, 720))
                self.frame.setStyleSheet("background-color: rgb(38, 87, 165);")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.labelTitulo = QtWidgets.QLabel(self.frame)
                self.labelTitulo.setGeometry(QtCore.QRect(387, 57, 528, 54))
                font = QtGui.QFont()
                font.setFamily("Open Sans Semibold")
                font.setPointSize(22)
                font.setBold(True)
                font.setWeight(75)
                self.labelTitulo.setFont(font)
                self.labelTitulo.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
                self.labelTitulo.setStyleSheet("background-color: rgb(226, 226, 226);\n"
        "border-radius: 27px;")
                self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
                self.labelTitulo.setObjectName("labelTitulo")
                self.label2 = QtWidgets.QLabel(self.frame)
                self.label2.setGeometry(QtCore.QRect(432, 127, 440, 519))
                font = QtGui.QFont()
                font.setFamily("Open Sans Semibold")
                font.setPointSize(22)
                font.setBold(True)
                font.setWeight(75)
                self.label2.setFont(font)
                self.label2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "border: 2px solid #000000;")
                self.label2.setText("")
                self.label2.setAlignment(QtCore.Qt.AlignCenter)
                self.label2.setObjectName("label2")
                self.labelFotoCasaPerro = QtWidgets.QLabel(self.frame)
                self.labelFotoCasaPerro.setGeometry(QtCore.QRect(762, 542, 91, 91))
                self.labelFotoCasaPerro.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.labelFotoCasaPerro.setText("")
                self.labelFotoCasaPerro.setPixmap(QtGui.QPixmap("imagenes/casaPerro.png"))
                self.labelFotoCasaPerro.setScaledContents(True)
                self.labelFotoCasaPerro.setObjectName("labelFotoCasaPerro")

                #Boton cerrar sesion
                self.btnCerrarSesion = QtWidgets.QPushButton(self.frame)
                self.btnCerrarSesion.setGeometry(QtCore.QRect(20, 640, 231, 61))
                font = QtGui.QFont()
                font.setFamily("Open Sans Semibold")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.btnCerrarSesion.setFont(font)
                self.btnCerrarSesion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.btnCerrarSesion.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "border-radius: 30px;\n"
        "border-width: 1px;\n"
        "border-color: rgb(0, 0, 0);\n"
        "border-style: solid;")
                self.btnCerrarSesion.setObjectName("btnCerrarSesion")

                #Accion boton cerrar sesion
                self.btnCerrarSesion.clicked.connect(self.cambiar_a_ventana_anterior)

                self.labelMedicamento = QtWidgets.QLabel(self.centralwidget)
                self.labelMedicamento.setGeometry(QtCore.QRect(450, 138, 62, 108))
                font = QtGui.QFont()
                font.setFamily("Open Sans Semibold")
                font.setPointSize(22)
                font.setBold(True)
                font.setWeight(75)
                self.labelMedicamento.setFont(font)
                self.labelMedicamento.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
                self.labelMedicamento.setStyleSheet("")
                self.labelMedicamento.setText("")
                self.labelMedicamento.setPixmap(QtGui.QPixmap("imagenes/Medicamento png.png"))
                self.labelMedicamento.setAlignment(QtCore.Qt.AlignCenter)
                self.labelMedicamento.setObjectName("labelMedicamento")
                self.labelPastilla = QtWidgets.QLabel(self.centralwidget)
                self.labelPastilla.setGeometry(QtCore.QRect(772, 137, 95, 97))
                font = QtGui.QFont()
                font.setFamily("Open Sans Semibold")
                font.setPointSize(22)
                font.setBold(True)
                font.setWeight(75)
                self.labelPastilla.setFont(font)
                self.labelPastilla.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
                self.labelPastilla.setStyleSheet("")
                self.labelPastilla.setText("")
                self.labelPastilla.setPixmap(QtGui.QPixmap("imagenes/Pastillas png.png"))
                self.labelPastilla.setAlignment(QtCore.Qt.AlignCenter)
                self.labelPastilla.setObjectName("labelPastilla")
                
                #Boton gestion de productos
                self.btnGestionDeProductos = QtWidgets.QPushButton(self.centralwidget)
                self.btnGestionDeProductos.setGeometry(QtCore.QRect(512, 250, 291, 71))
                font = QtGui.QFont()
                font.setFamily("Open Sans Semibold")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.btnGestionDeProductos.setFont(font)
                self.btnGestionDeProductos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.btnGestionDeProductos.setStyleSheet("border-color: rgb(0, 74, 173);")
                self.btnGestionDeProductos.setObjectName("btnGestionDeProductos")

                #Accion boton gestion de productos
                self.btnGestionDeProductos.clicked.connect(lambda:self.cambiar_ventana(uiListaProductos))

                #Boton venta de productos
                self.btnVentaDeProductos = QtWidgets.QPushButton(self.centralwidget)
                self.btnVentaDeProductos.setGeometry(QtCore.QRect(512, 450, 291, 71))
                font = QtGui.QFont()
                font.setFamily("Open Sans Semibold")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.btnVentaDeProductos.setFont(font)
                self.btnVentaDeProductos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.btnVentaDeProductos.setStyleSheet("border-color: rgb(0, 74, 173);")
                self.btnVentaDeProductos.setObjectName("btnVentaDeProductos")
                
                #Boton crear cliente
                self.btnCrearCliente = QtWidgets.QPushButton(self.centralwidget)
                self.btnCrearCliente.setGeometry(QtCore.QRect(512, 350, 291, 71))
                font = QtGui.QFont()
                font.setFamily("Open Sans Semibold")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.btnCrearCliente.setFont(font)
                self.btnCrearCliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.btnCrearCliente.setStyleSheet("border-color: rgb(0, 74, 173);")
                self.btnCrearCliente.setObjectName("btnCrearCliente")
                
                #Accion boton crear cliente
                self.btnCrearCliente.clicked.connect(lambda:self.cambiar_ventana(uiCrearCliente))

                #Accion boton venta de productos
                self.btnVentaDeProductos.clicked.connect(lambda:self.cambiar_ventana(uiVentaProductos))

                self.labelFotoComida = QtWidgets.QLabel(self.centralwidget)
                self.labelFotoComida.setGeometry(QtCore.QRect(442, 537, 121, 131))
                self.labelFotoComida.setText("")
                self.labelFotoComida.setPixmap(QtGui.QPixmap("imagenes/comidaPerro.png"))
                self.labelFotoComida.setScaledContents(True)
                self.labelFotoComida.setObjectName("labelFotoComida")
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.labelTitulo.setText(_translate("MainWindow", "TIENDA CLINICA CVI"))
                self.btnCerrarSesion.setText(_translate("MainWindow", "Cerrar Sesion"))
                self.btnGestionDeProductos.setText(_translate("MainWindow", "Gestion de productos"))
                self.btnVentaDeProductos.setText(_translate("MainWindow", "Venta de productos"))
                self.btnCrearCliente.setText(_translate("MainWindow", "Crear Cliente"))


        def cambiar_ventana(self, nombreVentana):
                self.uiVentanaActual = QtWidgets.QApplication.activeWindow()
                self.uiVentanaActual.close()
                self.nuevaVentana = QtWidgets.QMainWindow()
                self.ui = nombreVentana()
                self.ui.setupUi(self.nuevaVentana)
                self.nuevaVentana.show()

        
        def cambiar_a_ventana_anterior(self):
                self.ventanaActual = QtWidgets.QApplication.activeWindow()
                self.ventanaActual.close()
                from uiLoginUser import uiLogin  # Importación local para evitar el ciclo de importación
                self.ventanaAnterior = QtWidgets.QMainWindow(self.ventanaActual.parent())
                self.uiVentanaAnterior = uiLogin()
                self.uiVentanaAnterior.setupUi(self.ventanaAnterior)
                self.ventanaAnterior.show()
